Repository wersharks/flutter-101, pull requests merged in 2022-10, with the labels that each got.

#11 Added Flutter resources to learn
  Flutter_resources.md
Labels: hacktoberfest, hacktoberfest-accepted, flutter

#18 Updated readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#22 added destini app
  destini-app/.gitignore
  destini-app/.metadata
  destini-app/README.md
  destini-app/android/app/build.gradle
  destini-app/android/app/src/main/AndroidManifest.xml
  destini-app/android/app/src/main/java/co/appbrewery/destinichallengestarting/MainActivity.java
  destini-app/android/app/src/main/res/drawable/launch_background.xml
  destini-app/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  destini-app/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  destini-app/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  destini-app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  destini-app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  destini-app/android/app/src/main/res/values/styles.xml
  destini-app/android/build.gradle
  destini-app/android/gradle.properties
  destini-app/android/gradle/wrapper/gradle-wrapper.properties
  destini-app/android/settings.gradle
  destini-app/images/background.png
  destini-app/ios/Flutter/AppFrameworkInfo.plist
  destini-app/ios/Flutter/Debug.xcconfig
  destini-app/ios/Flutter/Release.xcconfig
  destini-app/ios/Flutter/flutter_export_environment.sh
  destini-app/ios/Runner.xcodeproj/project.pbxproj
  destini-app/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  destini-app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  destini-app/ios/Runner.xcworkspace/contents.xcworkspacedata
  destini-app/ios/Runner/AppDelegate.h
  destini-app/ios/Runner/AppDelegate.m
  destini-app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  destini-app/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
  destini-app/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  destini-app/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  destini-app/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  destini-app/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
  destini-app/ios/Runner/Base.lproj/LaunchScreen.storyboard
  destini-app/ios/Runner/Base.lproj/Main.storyboard
  destini-app/ios/Runner/Info.plist
  destini-app/ios/Runner/main.m
  destini-app/lib/main.dart
  destini-app/lib/story.dart
  destini-app/lib/story_brain.dart
  destini-app/pubspec.yaml
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#23 updated readme.md
  destini-app/README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#25 fixed the android v1 embedding issue in destini app
  destini-app/android/app/build.gradle
  destini-app/android/app/src/main/AndroidManifest.xml
  destini-app/android/build.gradle
  destini-app/android/gradle/wrapper/gradle-wrapper.properties
Labels: bug, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#27 Made some UI fixes including button style and text style
  destini-app/lib/main.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
